// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp2EI9MEm5U2zr9WCSDyru5uQOX-gtp6E',
    appId: '1:714271262674:web:c1244c67f42529d919aa0b',
    messagingSenderId: '714271262674',
    projectId: 'webapp-6f142',
    authDomain: 'webapp-6f142.firebaseapp.com',
    storageBucket: 'webapp-6f142.appspot.com',
    measurementId: 'G-KV20XD7S0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6GerAwUddmrDuzt2juDU-G2NWG2iy_wQ',
    appId: '1:714271262674:android:bfe967f27df6ebd619aa0b',
    messagingSenderId: '714271262674',
    projectId: 'webapp-6f142',
    storageBucket: 'webapp-6f142.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLiHCGAG-L5QJuyItncA3vVPOVvWaB6H4',
    appId: '1:714271262674:ios:c1a089dc25aeb82419aa0b',
    messagingSenderId: '714271262674',
    projectId: 'webapp-6f142',
    storageBucket: 'webapp-6f142.appspot.com',
    iosClientId: '714271262674-d181vkvj98m3fjulbe8osrvhibpev0dv.apps.googleusercontent.com',
    iosBundleId: 'com.example.webapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLiHCGAG-L5QJuyItncA3vVPOVvWaB6H4',
    appId: '1:714271262674:ios:a63e0060b94b7b4c19aa0b',
    messagingSenderId: '714271262674',
    projectId: 'webapp-6f142',
    storageBucket: 'webapp-6f142.appspot.com',
    iosClientId: '714271262674-1j3m45nr1r2fociu7b4v2deal3brreq2.apps.googleusercontent.com',
    iosBundleId: 'com.example.webapp.RunnerTests',
  );
}
